export const GAME_STATE = {
  MENU: 'MENU',
  MAP_SELECT: 'MAP_SELECT',
  EXPLORING: 'EXPLORING',
  COMBAT: 'COMBAT',
  LOOTING: 'LOOTING',
  CAMP: 'CAMP',
  GAME_OVER: 'GAME_OVER',
  VICTORY: 'VICTORY'
};

export const CARD_TYPES = {
  ATTACK: 'ATTACK',
  SKILL: 'SKILL',
  POWER: 'POWER'
};

export const STATUS_TYPES = {
  RADIATION: 'RADIATION',
  LOCK_ON: 'LOCK_ON',
  STUN: 'STUN'
};

export const ENEMY_INTENTS = {
  ATTACK: 'ATTACK',
  DEFEND: 'DEFEND',
  BUFF: 'BUFF',
  DEBUFF: 'DEBUFF',
  CHARGE: 'CHARGE',
  ESCAPE: 'ESCAPE',
  SLEEP: 'SLEEP'
};